version: '2'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD:/app
    ports:
      - 8080:8080
  aws:
    image: anigeo/awscli
    environment:
      AWS_ACCESS_KEY_ID: AKIAYI653BBOBJA4Q6NL
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: sa-east-1
      AWS_DEFAULT_REGION: sa-east-1
    volumes:
      - $PWD:/app
    working_dir: /app    
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    environment:
      AWS_ACCESS_KEY_ID: AKIAYI653BBOBJA4Q6NL
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: sa-east-1
      AWS_DEFAULT_REGION: sa-east-1
    volumes:
      - $PWD:/app
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
  integration-tests:
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - "$PWD:/app"
    build:
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb
  website:
   build:
    context: .
   ports:
    - 80:80
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
